### ISSUE TITLE
Potential vulnerabilities in Puppet file: Use of HTTP without TLS

### ISSUE THREAD

**Issue by cantebigene** [vincentbernat/puppet-workstation#2]
The following script seems to have 5 configurations of HTTP without TLS: https://github.com/vincentbernat/puppet-workstation/blob/7cf64fdd48e6e70a8253fa29d58715b10867afda/local-modules/debian/manifests/init.pp

Line [28](https://github.com/vincentbernat/puppet-workstation/blob/7cf64fdd48e6e70a8253fa29d58715b10867afda/local-modules/debian/manifests/init.pp#L28): http://httpredir.debian.org/debian/
Line [34](https://github.com/vincentbernat/puppet-workstation/blob/7cf64fdd48e6e70a8253fa29d58715b10867afda/local-modules/debian/manifests/init.pp#L34): http://debug.mirrors.debian.org/debian-debug/
Line [40](https://github.com/vincentbernat/puppet-workstation/blob/7cf64fdd48e6e70a8253fa29d58715b10867afda/local-modules/debian/manifests/init.pp#L40): http://httpredir.debian.org/debian/
Line [46](https://github.com/vincentbernat/puppet-workstation/blob/7cf64fdd48e6e70a8253fa29d58715b10867afda/local-modules/debian/manifests/init.pp#L46): http://httpredir.debian.org/debian/
Line [52](https://github.com/vincentbernat/puppet-workstation/blob/7cf64fdd48e6e70a8253fa29d58715b10867afda/local-modules/debian/manifests/init.pp#L52): http://debug.mirrors.debian.org/debian-debug/

This type of smell can lead to a well-known type of vulnerability, as documented by CWE ([CWE-546](https://cwe.mitre.org/data/definitions/546.html)). Using HTTP without TLS to communicate with other servers/sources gives access to sensitive or security-critical data in cleartext to unauthorized actors during network communication/traffic (e.g., man-in-the-middle attacks).

Configuring HTTP without using TLS in **Puppet** configuration files is considered to be a security smell (cf. [[icse19](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]).

**Recommendation**
You can instead use HTTPS (HTTP using TLS) to protect the privacy and integrity of the exchanged data. For instance, replace `$auth_url = ‘http://127.0.0.1:35357/’` by `$auth_url = ‘https://127.0.0.1:35357/’`. Thus, you will highly decrease the chances of having your app data leaked.

**Comment by vincentbernat** [comment]
Debian mirrors are authenticated by GPG signatures. Confidentiality is not a problem as the content is public.
